
addons:
  postgresql: '9.4'
  mariadb: '10.0'

language: node_js
node_js:
  - 10
  - 9
  - 8
  - 6

before_script:
  - mysql -e 'CREATE DATABASE async_db_adapter CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
  - psql -c 'CREATE DATABASE async_db_adapter;' -U postgres

script:
  - npm test
