version: '3'

services:
  postgres9.6:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stdjs_database
    ports:
      - 5432
  mariadb10.0:
    image: mariadb:10.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: stdjs_database
    ports:
      - 3306
