version: '3'

services:
  postgres9.6:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stdjs_database
    ports:
      - 5432
  mariadb10.0:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: stdjs_database
    ports:
      - 3306
  memcached:
    image: memcached:alpine
    ports:
      - 11211
  redis:
    image: redis:alpine
    ports:
      - 6379
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672
